package corpus

import (
	"fmt"
	"image"
	"image/color"
	"math"
	"math/rand/v2"
)

// syntheticSizes: a phone-sized screen, and an A4 page at 150 and 300 dpi.
var syntheticSizes = []struct {
	size string
	w, h int
}{
	{Small, 360, 640},
	{Medium, 1240, 1754},
	{Large, 2480, 3508},
}

// synthetic images isolate one property each and are reported apart from
// the real ones: a page of text-like strokes, a user interface, a smooth
// photo-like gradient with noise, flat colour and pure noise (the high
// entropy extreme).
func synthetic() []Fixture {
	gens := []struct {
		name  string
		short bool
		gen   func(w, h int) image.Image
	}{
		{"page", true, page},
		{"ui", false, ui},
		{"gradient-noise", false, gradientNoise},
		{"flat", false, flat},
		{"noise", true, noise},
	}
	var out []Fixture
	for _, g := range gens {
		for _, s := range syntheticSizes {
			name := fmt.Sprintf("synthetic/%s/%s-%dx%d", s.size, g.name, s.w, s.h)
			out = append(out, Fixture{
				Name: name, Category: "synthetic", Size: s.size,
				Short:   g.short && s.size == Medium,
				Source:  "generated by bench/corpus",
				License: "MIT, generated",
				load:    func(string, []byte) (image.Image, error) { return g.gen(s.w, s.h), nil },
			})
		}
	}
	return out
}

// page is mostly white with thin dark strokes in lines, like rendered text.
func page(w, h int) image.Image {
	r := rand.New(rand.NewPCG(5, 6))
	m := image.NewRGBA(image.Rect(0, 0, w, h))
	for i := range m.Pix {
		m.Pix[i] = 0xff
	}
	mx, my := w/12, h/14
	for line := my; line < h-my-12; line += max(8, h/80) {
		for x := mx; x < w-mx; x++ {
			if (x/7+line)%9 == 0 {
				continue // word gaps
			}
			for dy := range max(4, h/146) {
				if r.IntN(3) == 0 {
					v := uint8(r.IntN(90))
					m.SetRGBA(x, line+dy, color.RGBA{v, v, v, 0xff})
				}
			}
		}
	}
	return m
}

// ui has flat panels, edges and text-like detail.
func ui(w, h int) image.Image {
	m := image.NewRGBA(image.Rect(0, 0, w, h))
	side := w / 5
	for y := range h {
		for x := range w {
			c := color.RGBA{0xf6, 0xf7, 0xf9, 0xff}
			switch {
			case x < side:
				c = color.RGBA{0x24, 0x29, 0x2f, 0xff}
			case y%120 < 36 && x > side+40 && x < w-40:
				c = color.RGBA{0xff, 0xff, 0xff, 0xff}
				if (x+y)%17 < 3 && y%120 > 12 && y%120 < 24 {
					c = color.RGBA{0x1f, 0x23, 0x28, 0xff}
				}
			}
			m.SetRGBA(x, y, c)
		}
	}
	return m
}

// gradientNoise is smooth colour with a little noise, like a photo.
func gradientNoise(w, h int) image.Image {
	r := rand.New(rand.NewPCG(5, 6))
	m := image.NewRGBA(image.Rect(0, 0, w, h))
	for y := range h {
		for x := range w {
			fx, fy := float64(x)/float64(w), float64(y)/float64(h)
			n := uint8(r.IntN(12))
			m.SetRGBA(x, y, color.RGBA{
				uint8(120+100*math.Sin(fx*7+fy*3)) + n,
				uint8(100+80*math.Cos(fy*5)) + n,
				uint8(90+60*math.Sin(fx*fy*11)) + n, 0xff})
		}
	}
	return m
}

// flat is a few rectangles of solid colour.
func flat(w, h int) image.Image {
	m := image.NewRGBA(image.Rect(0, 0, w, h))
	cs := []color.RGBA{{0x2e, 0x86, 0xab, 0xff}, {0xf2, 0x4c, 0x00, 0xff}, {0xff, 0xff, 0xff, 0xff}, {0x3a, 0x3a, 0x3a, 0xff}}
	for y := range h {
		for x := range w {
			m.SetRGBA(x, y, cs[(2*x/w)+2*(2*y/h)])
		}
	}
	return m
}

// noise is uniformly random opaque colour: nothing to compress.
func noise(w, h int) image.Image {
	r := rand.New(rand.NewPCG(9, 10))
	m := image.NewRGBA(image.Rect(0, 0, w, h))
	for i := range m.Pix {
		m.Pix[i] = uint8(r.Uint32())
		if i%4 == 3 {
			m.Pix[i] = 0xff
		}
	}
	return m
}
